### ISSUE TITLE
Draw tools are selectable while in tax lot selection mode

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#109] opened 2018-09-24 20:20 UTC
You can enter tax lot selection mode, then click the draw tools and start drawing. This is potentially confusing. When you enter tax lot selection mode, drawing should stop and the controls should hide.

**Comment by allthesignals** [comment] 2018-09-26 18:10
Is that a priority for this week? Does it break anything? Or is it just confusing?

**Comment by allthesignals** [comment] 2018-09-26 18:15
This is also a duplicate of #121

**Comment by andycochran** [comment] 2018-09-26 20:34
Doesn't _break_ anything. Just confusing and potentially frustrating, since you can spend time drawing a detailed shape not knowing you're in tax lot selection mode then lose all that work.

**Comment by andycochran** [comment] 2018-09-26 20:34
This is unrelated to #121.

**Comment by chriswhong** [comment] 2018-10-05 18:38
No longer relevant!  @andycochran fixed it

**Closed by chriswhong** 2018-10-05 18:38 UTC
Labels: Next Sprint, bug
