### ISSUE TITLE
User should not see the wizard after completing wizard / viewing dashboard. 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#538] opened 2019-05-06 19:09 UTC
Once you complete the wizard and view the dashboard, you should never see the wizard again. 

Here are some bugs related to the wizard, redirects, and back/cancel buttons: 

- [x] Currently, the app is loading the `/projects/[id]/edit/complete` view when you refresh `/projects/[id]` after viewing the dashboard. (see https://github.com/NYCPlanning/labs-applicantmaps-api/pull/11)

- [x] From the dashboard, if you click the + to add Underlying Zoning, then click "back", you're brought to the rezoning wizard question. You should be taken back to the dashboard, since you've completed the wizard. 

- [x] From the dashboard, if you click the + to add a Commercial Overlay, the back button points to `/projects/[id]/edit/geometry-edit?mode=draw&type=underlying-zoning` (the Underlying Zoning draw mode). If you don't click "back", and refresh the page, "back" changes to "cancel" and appropriately points to `/projects/[id]/` (tho it redirects to `complete`, as mentioned above).

**Comment by allthesignals** [comment] 2019-05-20 19:05
@andycochran why did you make this a single issue with checkboxes? Next time just open separate issues. 

The first checkbox is caused by a missing property in the model, `hasCompletedWizard`. The following test passes when that data comes back:
```
    this.server.create('project', {
      projectName: 'test',
      applicantName: 'test',
      zapProjectId: 'test',
      needDevelopmentSite: true,
      needProjectArea: false,
      needRezoning: false,
      hasCompletedWizard: true,
    });

    await visit('/projects/1');

    assert.equal(currentURL(), '/projects/1');
```

**Comment by allthesignals** [comment] 2019-05-20 19:13
The reason the second checkbox happens is that hitting `+ underlying zoning` and transitioning to that route implicitly sets the project to "needUnderlyingZoning". Let's see if we can change that up...

**Comment by allthesignals** [comment] 2019-05-20 19:15
These are not bugs so let's work on the definition of that a little bit. None of the behaviors in the checkboxes prevents a user from doing something in the app. This seems more like a luxury enhancement than a bug.

**Comment by allthesignals** [comment] 2019-05-20 19:53
A nuance missing from the design spec here is whether or not adding an optional geometric property means implicitly that the user "needs" that? I'm not sure that's the case. "needs"-related state seem important exclusively to the wizard portion of the application.

**Comment by hannahkates** [comment] 2020-04-30 02:10
Closing - No longer seems to be an issue.

**Closed by hannahkates** 2020-04-30 02:10 UTC
