### ISSUE TITLE
Applicant can draw project on a basemap that resembles the DOF's current tax mapper with zoning districts

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#7] opened 2018-06-04 15:47 UTC

**Comment by andycochran** [comment] 2018-06-04 15:48
http://gis.nyc.gov/taxmap/map.htm

**Comment by hannahkates** [comment] 2018-11-06 20:36
Duplicate of #104

**Closed by hannahkates** 2018-11-06 20:36 UTC
Labels: Strategic
