### ISSUE TITLE
Applicant can define their project area on the map

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#3] opened 2018-06-04 15:31 UTC

**Comment by allthesignals** [comment] 2018-06-05 14:49
Maybe they can draw, select or plot radius? The resulting geometry is the project area - if it's a select, it's whatever the geometry is for the selection.

**Comment by chriswhong** [comment] 2018-09-17 16:04
Dupe of #27

**Closed by chriswhong** 2018-09-17 16:04 UTC
Labels: to do
