### ISSUE TITLE
Commercial Overlays don't show up in legend of map when printed to pdf/printer

### ISSUE THREAD

**Issue by vvvo** [NYCPlanning/labs-applicantmaps#585] opened 2020-04-03 13:14 UTC
This seems to be a new problem that wasn't there before:

When the maps are printed to pdf or printer, the commercial overlays don't show up in the legend. See below:

![AMT_Missing C-Overlays](https://user-images.githubusercontent.com/43350235/78364459-78741980-758b-11ea-8607-71f614b4b64d.JPG)

**Comment by vvvo** [comment] 2020-06-30 13:44
@hannahkates @allthesignals  Just following up on this issue - all maps being produced by applicants are still running into this issue...

**Comment by allthesignals** [comment] 2020-07-16 19:03
@hannahkates we probably need to set up some maintenance time for this app

**Comment by rtblair** [comment] 2023-03-13 15:54
Closing this as a duplicate of #565.

**Closed by rtblair** 2023-03-13 15:54 UTC
Labels: Greenskeeper, Sev3 Bug
