### ISSUE TITLE
Applicant can create/print a Tax Map

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#10] opened 2018-06-04 15:54 UTC
This is tied to the Client + API - after whiteboarding, we now have a concept of a project:
Project  has many Maps[1,2,3,...]

The Map object can be of any type.

**Comment by hannahkates** [comment] 2018-11-06 20:35
Duplicate of #104

**Closed by hannahkates** 2018-11-06 20:35 UTC
